title: Meha Patel
description: >- # your tagline here
  Data scientist | Statistician | Educator
theme: jekyll-theme-minimal

# Optional settings:
show_downloads: true
google_analytics: # your tracking ID here (if any)
